language: ruby

rvm:
  - "2.1"
  - "2.0"
  - "1.9"

before_install:
  - git config --global user.email "dummy@localhost"
  - git config --global user.name "This Is Dummyyy"

install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES="YES"
  - travis_retry bundle install --jobs=3
  - bundle exec rake install

script:
  - bundle exec rake spec

deploy:
  provider: rubygems
  api_key:
    master:
      secure: "LjL6NrPR/KdkSKgUgixtsWiPH7LZrgZrMG9d66G0CY1HLDUXOY17W7HyAP0PYFVLVrJDM7CRx66PSuadYtyuIY1s0iM5hpEA81MlenxZQoApGcbJb2Zd647SPNk4NM+mZCRt9xJyRqrvHHg1d5+4pQVSHl/lGvuQRGXrYXocGLg="
  gem:
    master: git-contest

